// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGmbCLdvShDG7jHXA8WdNzhxsTwTNUvqQ',
    appId: '1:133282787504:web:c43b928ac1016442468b75',
    messagingSenderId: '133282787504',
    projectId: 'keidaiart-cc9c8',
    authDomain: 'keidaiart-cc9c8.firebaseapp.com',
    storageBucket: 'keidaiart-cc9c8.appspot.com',
    measurementId: 'G-98887RXDVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClfbH82F_J5_WrJVAL2H8q_Lcm6SkUkPo',
    appId: '1:133282787504:android:fbdcaa541d410d05468b75',
    messagingSenderId: '133282787504',
    projectId: 'keidaiart-cc9c8',
    storageBucket: 'keidaiart-cc9c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKrGYuxtN6feRRuig4Dzu9MCrbWNkFW_I',
    appId: '1:133282787504:ios:0e113a4c74808e87468b75',
    messagingSenderId: '133282787504',
    projectId: 'keidaiart-cc9c8',
    storageBucket: 'keidaiart-cc9c8.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKrGYuxtN6feRRuig4Dzu9MCrbWNkFW_I',
    appId: '1:133282787504:ios:92cbdf4d3cc8638a468b75',
    messagingSenderId: '133282787504',
    projectId: 'keidaiart-cc9c8',
    storageBucket: 'keidaiart-cc9c8.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
